# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

flutter_application_path = "../crm_app/my_flutter"
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'flutter_crm_ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for flutter_crm_ios

end
